config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    sessions: 'users/sessions' }

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    get 'archive',         to: 'orders#archive'
    get 'change_status',   to: 'orders#change_status'
    get 'delivered',       to: 'orders#delivered'
    get 'mailbox/inbox',   to: 'mailbox#inbox'
    get 'mailbox/sentbox', to: 'mailbox#sentbox'
    get 'taken',           to: 'orders#taken'
    get 'taken_orders',    to: 'orders#taken_orders'

    resources :avatars, except: %i[index show]
    resources :conversations do
      member do
        delete :destroy_message
        post :reply
      end
    end
    resources :notifications, only: %i[destroy index] do
      post :mark_as_read, on: :collection
    end
    resources :orders
    resources :users do
      member do
        post :enable_multi_factor_authentication,
          to: 'users/multi_factor_authentication#verify_enable'
        post :disable_multi_factor_authentication,
          to: 'users/multi_factor_authentication#verify_disabled'
      end
      resources :reviews
    end

    root 'orders#index'
  end
end

app/controllers/conversations_controller.rb
# frozen_string_literal: true

class ConversationsController < ApplicationController
  def new
    @user = User.find(params[:user_id])
  end

  def create
    recipient = User.find(conversation_params[:recipient])
    receipt = current_user.send_message(recipient, conversation_params[:body], recipient)

    redirect_to conversation_path(receipt.conversation)
  end

  def show
    @receipts = conversation.receipts_for(current_user).order(:created_at).where(deleted: false)

    conversation.mark_as_read(current_user)
  end

  def destroy
    conversation.mark_as_deleted(current_user)
    redirect_to mailbox_inbox_path
  end

  def destroy_message
    message = Mailboxer::Message.find(params[:msg_id])
    current_user.mark_as_deleted message

    redirect_back(fallback_location: root_path)
  end

  def reply
    current_user.reply_to_conversation(conversation, message_params[:body])

    redirect_to conversation_path(conversation)
  end

  private

  def conversation_params
    params.require(:conversation).permit(:body, :subject, :recipient)
  end

  def message_params
    params.require(:message).permit(:body, :subject)
  end
end

app/helpers/conversations_helper.rb
# frozen_string_literal: true

module ConversationsHelper
  def recipient(conversation)
    conversation.recipients.reject { |user| user == current_user }.first
  end

  def unread?(conversation)
    conversation.is_unread?(current_user) ? 'unread' : ''
  end
end

app/views/conversations/_conversation.html.erb
<div class="list-group conversations">
  <%= link_to conversation_path(conversation), class: "#{unread?(conversation)} list-group-item list-group-item-action" do %>
    <% if conversation.originator == current_user %>
      <%= render 'conversations/conversation_body', user: recipient(conversation), conversation: conversation %>
    <% else %>
      <%= render 'conversations/conversation_body', user: conversation.originator, conversation: conversation %>
    <% end %>
    <%= (truncate conversation.last_message.body, length: 75) %>
  <% end %>
</div>

app/views/conversations/_conversation_body.html.erb
<h4 class="heading">
  <div class="conversation">
    <% user_photo(user, 66) %>
  </div>
  <b><%= user.full_name %></b>
  <small class="conversation-timestamp">
    <%=  conversation.last_message.created_at.strftime("%b %d, %Y, %H:%M") %>
  </small>
</h4>
<% unless conversation.last_message.sender == user %>
  <% user_photo(conversation.last_message.sender, 35) %>
<% end %>

app/views/conversations/_form.html.erb
<%= form_for :conversation, url: conversations_path do |f| %>
  <%= f.hidden_field :recipient, value: params[:user_id] %>

  <div class="form-group">
    <%= f.label :message, t('.message') %>
    <%= f.text_area :body, placeholder: t('.placeholder'), class: "form-control" %>
  </div>

  <%= f.submit t('.send'), class: "btn btn-success" %>
<% end %>

app/views/conversations/_messages.html.erb
<% @receipts.each do |receipt| %>
  <div class="card conversations">
    <div class="card-body">
      <div class="heading">
        <div class="conversation">
          <% user_photo(receipt.message.sender, 66) %>
        </div>
        <b><%= link_to receipt.message.sender.first_name, user_path(receipt.message.sender) %></b><br>
        <small><%= receipt.message.created_at.strftime("%b %d, %Y at %H:%M") %></small>
        <%= link_to destroy_message_conversation_path(conversation, msg_id: receipt.message),
                      method: :delete, title: t('common.delete'), class: "btn btn-outline-danger delete" do %>
          <%= fa_icon 'times' %>
        <% end %>
      </div>
      <hr>
      <%= receipt.message.body %>
    </div>
  </div>
<% end %>

app/views/conversations/new.html.erb
<% provide(:title, t('title.new_message')) %>

<h1 class="text-center"><%= t('.title') %></h1>
<hr>

<div class="text-center">
  <% user_photo(@user, 80) %>
  <%= @user.full_name %>
</div>

<div class="form-container">
  <%= render 'form' %>
</div>

app/views/conversations/show.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="card">
      <div class="card-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="card">
      <div class="col-md-12 text-center conversations">
        <%= link_to conversation_path(conversation), method: :delete, class: "btn btn-danger pull-right" do %>
          <em class="fa fa-trash-o fa-lg"></em>
          <span><%= t('.delete_conversation') %></span>
        <% end %>
      </div>
      <div class="card-body">
        <%= render partial: 'messages' %>
      </div>
      <div class="card-footer">
        <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
          <div class="form-group mb-2">
            <%= f.text_area :body, placeholder: t('conversations.form.placeholder'), class: "form-control" %>
          </div>
          <%= f.submit t('conversations.form.send'), class: "btn btn-success pull-right  mb-2" %>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>
</div>