config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    sessions: 'users/sessions' }

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    get 'archive',         to: 'orders#archive'
    get 'change_status',   to: 'orders#change_status'
    get 'delivered',       to: 'orders#delivered'
    get 'mailbox/inbox',   to: 'mailbox#inbox'
    get 'mailbox/sentbox', to: 'mailbox#sentbox'
    get 'taken',           to: 'orders#taken'
    get 'taken_orders',    to: 'orders#taken_orders'

    resources :avatars, except: %i[index show]
    resources :conversations do
      member do
        delete :destroy_message
        post :reply
      end
    end
    resources :notifications, only: %i[destroy index] do
      post :mark_as_read, on: :collection
    end
    resources :orders
    resources :users do
      member do
        post :enable_multi_factor_authentication,
          to: 'users/multi_factor_authentication#verify_enable'
        post :disable_multi_factor_authentication,
          to: 'users/multi_factor_authentication#verify_disabled'
      end
      resources :reviews
    end

    root 'orders#index'
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :otp_code_token

  enum otp_module: %i[disabled enabled], _prefix: true

  has_many :notifications, dependent: :destroy, foreign_key: :recipient_id
  has_many :reviews,       dependent: :destroy
  has_many :orders,        dependent: :nullify

  has_one  :avatar,        dependent: :destroy

  delegate :image, to: :avatar, allow_nil: true

  scope :drivers, -> { where(driver: true) }

  validates :email, :first_name, :last_name, presence: true

  acts_as_messageable
  has_one_time_password

  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
    :trackable, :validatable, :omniauthable,
    omniauth_providers: %i[facebook google_oauth2]

  def full_name
    "#{first_name} #{last_name}"
  end

  def mailboxer_email(_object)
    email
  end

  def mailboxer_name
    name
  end

  def not_driver?
    driver.blank?
  end

  def photo?
    avatar.present?
  end
end

app/controllers/users/multi_factor_authentication_controller.rb
# frozen_string_literal: true

class Users::MultiFactorAuthenticationController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user

  def verify_enable
    if current_user == @user &&
       current_user.authenticate_otp(
         params[:multi_factor_authentication][:otp_code_token], drift: 60
       )
      current_user.otp_module_enabled!
      redirect_to edit_user_registration_path, notice: t('tfa.enabled')
    else
      redirect_to edit_user_registration_path, alert: t('tfa.not_be_enabled')
    end
  end

  def verify_disabled
    if current_user == @user &&
       current_user.authenticate_otp(
         params[:multi_factor_authentication][:otp_code_token], drift: 60
       )
      current_user.otp_module_disabled!
      redirect_to edit_user_registration_path, notice: t('tfa.disabled')
    else
      redirect_to edit_user_registration_path, alert: t('tfa.not_be_disabled')
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    authenticate('Facebook')
  end

  def google_oauth2
    authenticate('Google')
  end

  private

  def authenticate(kind)
    @user = AuthenticationService.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: kind) if is_navigational_format?
    else
      redirect_to new_user_session_path, alert: t('common.omniauth.error')
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def create
    self.resource = warden.authenticate!(auth_options)

    if resource&.otp_module_disabled?
      continue_sign_in(resource, resource_name)

    elsif resource&.otp_module_enabled?

      if params[:user][:otp_code_token].size.positive?
        authenticate_otp
      else
        sign_out resource
        redirect_to root_url, alert: t('tfa.needs_token')
      end

    end
  end

  def authenticate_otp
    if resource.authenticate_otp(params[:user][:otp_code_token], drift: 60)
      continue_sign_in(resource, resource_name)
    else
      sign_out resource
      redirect_to root_url, alert: t('tfa.bad_credential')
    end
  end

  private

  def continue_sign_in(resource, resource_name)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @reviews = Review.all.paginate(page: params[:page])
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def user_photo(user, width = 250)
    if user.photo?
      concat image_tag user.image.url(:thumb), width: width, class: 'img-thumbnail'
    else
      concat image_tag 'noavatar.png', width: width, class: 'img-thumbnail'
    end
  end
end

app/views/users/_avatar_control_links.html.erb
<% if @user.photo? && @user == current_user %>
  <%= link_to 'delete avatar', avatar_path(@user.avatar), method: :delete %> |
  <%= link_to 'change avatar', edit_avatar_path(@user.avatar) %>
<% else %>
  <%= link_to 'add avatar', new_avatar_path if @user == current_user %>
<% end %>

app/views/users/_review_form.html.erb
<div class="profile">
  <h2><%= t('.title') %></h2>
  <%= form_with(model: [ @user, @user.reviews.build ], local: true) do |form| %>
    <div class="stars">
      <%= form.radio_button :rating, 5, id: 'star-5', class: "star star-5" %>
      <label class="star star-5" for="star-5" title="<%= t('.rating.excellent') %>"></label>
      <%= form.radio_button :rating, 4, id: 'star-4', class: "star star-4" %>
      <label class="star star-4" for="star-4" title="<%= t('.rating.good') %>"></label>
      <%= form.radio_button :rating, 3, id: 'star-3', class: "star star-3" %>
      <label class="star star-3" for="star-3" title="<%= t('.rating.fine') %>"></label>
      <%= form.radio_button :rating, 2, id: 'star-2', class: "star star-2" %>
      <label class="star star-2" for="star-2" title="<%= t('.rating.so-so') %>"></label>
      <%= form.radio_button :rating, 1, id: 'star-1', class: "star star-1" %>
      <label class="star star-1" for="star-1" title="<%= t('.rating.bad') %>"></label>
    </div>

    <div class="form-group">
      <%= form.label t('.comment') %>
      <%= form.text_area :body, required: true, placeholder: t('.placeholder'), class: "form-control" %>
    </div>
    <%= form.submit t('.send'), class: "btn btn-default" %>
  <% end %>
</div>

app/views/users/_reviews.html.erb
<% @reviews.for_driver(@user).each do |review| %>
  <div class="profile">
    <b><%= review.user.full_name %></b>
    <% show_rating(review.rating) %>
    <%= link_to user_review_path(@user, review), method: :delete, title: t('common.delete'), class: "pull-right" do %>
      <%= fa_icon 'times' %>
    <% end if review.user == current_user %>
    <hr>
    <%= review.body %><br>
  </div>
<% end %>

<%= will_paginate @reviews.for_driver(@user) %>

app/views/users/show.html.erb
<% provide(:title, t('title.profile')) %>

<div class="profile">
  <h2 class="text-center"><%= @user.full_name %></h2>
  <hr>

  <div class="modal-body">
    <center>
      <% user_photo(@user) %><br>
      <%= render 'avatar_control_links' %><br>
      <%= t('.rating') %>:
      <% rating_for_user(@user) %>
      <hr>
    <center>
      <p>
        <%= t('.phone') %>:
        <%= @user.phone %>
      </p>
      <p>
        <%= t('.email') %>:
        <%= @user.email %>
      </p>
      <% if @user == current_user %>
        <%= link_to t('common.edit_profile'), edit_user_registration_path, class: "btn btn-info"  %>
      <% else %>
        <%= link_to t('.message'), new_conversation_path(user_id: @user.id), class: "btn btn-success" %>
      <% end %>
    </center>
  </div>
</div>

<%= render 'reviews' %>

<%= render 'review_form' unless @user == current_user %>