config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    sessions: 'users/sessions' }

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    get 'archive',         to: 'orders#archive'
    get 'change_status',   to: 'orders#change_status'
    get 'delivered',       to: 'orders#delivered'
    get 'mailbox/inbox',   to: 'mailbox#inbox'
    get 'mailbox/sentbox', to: 'mailbox#sentbox'
    get 'taken',           to: 'orders#taken'
    get 'taken_orders',    to: 'orders#taken_orders'

    resources :avatars, except: %i[index show]
    resources :conversations do
      member do
        delete :destroy_message
        post :reply
      end
    end
    resources :notifications, only: %i[destroy index] do
      post :mark_as_read, on: :collection
    end
    resources :orders
    resources :users do
      member do
        post :enable_multi_factor_authentication,
          to: 'users/multi_factor_authentication#verify_enable'
        post :disable_multi_factor_authentication,
          to: 'users/multi_factor_authentication#verify_disabled'
      end
      resources :reviews
    end

    root 'orders#index'
  end
end

app/views/shared/_footer.html.erb
<footer id="myFooter" class="footer">
  <div class="container mt-2">
    <div class="row">
      <div class="col-sm-3 sss">
        <div class="logo">
          <%= link_to root_url, title: t('common.home_page'), class: "navbar-logo" do %>
            <%= (image_tag "logo.png", width: "150") %>
          <% end %>
        </div>
        <h3 class="text-logo">trucking</h3>
      </div>
      <div class="col-sm-2">
        <h5>Get started</h5>
        <ul>
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        </ul>
      </div>
      <div class="col-sm-2">
        <h5>About us</h5>
        <ul>
          <li><a href="#">Company Information</a></li>
          <li><a href="#">Contact us</a></li>
        </ul>
      </div>
      <div class="col-sm-5">
        <div class="social-networks">
          <a href="https://www.instagram.com/russ.oliinyk/" class="instagram" target="_blank"><i class="fa fa-instagram"></i></a>
          <a href="https://vk.com/russ.oliinyk" class="vk" target="_blank"><i class="fa fa-vk"></i></a>
          <a href="https://plus.google.com/u/0/+russ1turnikmen" class="google" target="_blank"><i class="fa fa-google-plus"></i></a>
          <a href="https://www.facebook.com/oliinyk.ruslan" class="facebook" target="_blank"><i class="fa fa-facebook"></i></a>
          <a href="https://twitter.com/russ_oliinyk" class="twitter" target="_blank"><i class="fa fa-twitter"></i></a>
        </div>
        <button type="button" class="btn btn-default">Contact us</button>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <p>© 2018 All right reserved </p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to root_url, title: t('common.home_page'), class: "navbar-brand" do %>
    <%= (image_tag "logo.png", width: "50") %>
    Trucking
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse navbar-right" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <% if current_user.driver %>
          <li class="nav-item">
            <%= link_to t('common.taken_orders'), taken_orders_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to t('common.archive'), archive_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to mailbox_inbox_path, class: "nav-link" do %>
            <%= t('common.conversations') %>
            <span class="badge badge-light"><%= unread_messages_count %></span>
          <% end %>
        </li>
      <% end %>
    </ul>

    <% if user_signed_in? %>
      <ul class="navbar-nav mr-right mr-2">
        <li class="nav-item dropdown" data-behavior="notifications">
          <a class="nav-link dropdown-toggle" href="#" data-behavior="notification-links" id="notificationDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= fa_icon 'bell', class: "fa-lg fa-inverse" %><span class="badge badge-pill badge-info" data-behavior="unread-count">0</span>
          </a>
            <div class="dropdown-menu fix-nav" aria-labelledby="notificationDropdown" data-behavior="notification-items">
              <a class='dropdown-item'><b><%= t('common.no_notify') %></b></a>
              <div class="dropdown-divider"></div>
              <%= link_to t('notifications.show_all'), notifications_path, class: "dropdown-item link-style" %>
            </div>
        </li>
      </ul>
    <% end %>

    <ul class="navbar-nav mr-right">
      <li class="nav-item dropdown mr-2">
        <a class="nav-link dropdown-toggle" href="#" id="languageDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= I18n.locale.upcase %> <%= image_tag "#{I18n.locale}.png", width: '20' if  File.file? "app/assets/images/#{I18n.locale}.png" %>
        </a>
        <div class="dropdown-menu dropdown-links" aria-labelledby="languageDropdown">
          <%= link_to locale: :en do %>
            Eng
            <%= image_tag "en.png", width: '20' if  File.file? "app/assets/images/en.png" %>
          <% end %>
          <div class="dropdown-divider"></div>
          <%= link_to locale: :ua do %>
            Укр
            <%= image_tag "ua.png", width: '20' if  File.file? "app/assets/images/ua.png" %>
          <% end %>
          <div class="dropdown-divider"></div>
          <%= link_to locale: :ru do %>
            Рус
            <%= image_tag "ru.png", width: '20' if  File.file? "app/assets/images/ru.png" %>
          <% end %>
        </div>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= link_to user_path(current_user), class: "nav-link dropdown-toggle", id: "navbarDropdown", role: "button", data: { toggle: "dropdown" } do %>
            <% if current_user.photo? %>
              <%= image_tag current_user.image.url(:thumb), width: 28, class: 'img-border' %>
            <% else %>
              <%= image_tag 'noavatar.png', width: 28, class: 'img-border' %>
            <% end %>
            <%= current_user.first_name %>
          <% end %>
          <div class="dropdown-menu fix-nav" aria-labelledby="navbarDropdown">
            <%= link_to user_path(current_user), class: "dropdown-item" do %>
              <i class="fa fa-user" aria-hidden="true"> <%= t('.profile') %></i>
            <% end %>
            <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
              <i class="fa fa-wrench" aria-hidden="true"> <%= t('.settings') %></i>
            <% end %>
            <div class="dropdown-divider"></div>
            <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
              <i class="fa fa-sign-out" aria-hidden="true"> <%= t('common.sign_out') %></i>
            <% end %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to t('common.sign_in'), new_user_session_path, class: "btn btn-outline-warning mr-sm-2" %>
        </li>
        <li class="nav-item">
          <%= link_to t('common.sign_up'), new_user_registration_path, class: "btn btn-outline-success" %>
        </li>
      <% end %>



    </ul>
  </div>
</nav>