config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    sessions: 'users/sessions' }

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    get 'archive',         to: 'orders#archive'
    get 'change_status',   to: 'orders#change_status'
    get 'delivered',       to: 'orders#delivered'
    get 'mailbox/inbox',   to: 'mailbox#inbox'
    get 'mailbox/sentbox', to: 'mailbox#sentbox'
    get 'taken',           to: 'orders#taken'
    get 'taken_orders',    to: 'orders#taken_orders'

    resources :avatars, except: %i[index show]
    resources :conversations do
      member do
        delete :destroy_message
        post :reply
      end
    end
    resources :notifications, only: %i[destroy index] do
      post :mark_as_read, on: :collection
    end
    resources :orders
    resources :users do
      member do
        post :enable_multi_factor_authentication,
          to: 'users/multi_factor_authentication#verify_enable'
        post :disable_multi_factor_authentication,
          to: 'users/multi_factor_authentication#verify_disabled'
      end
      resources :reviews
    end

    root 'orders#index'
  end
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  enum status: %i[new_order taken delivered]

  belongs_to :driver, class_name: 'User', optional: true
  belongs_to :user

  has_many :notifications, as: :notifiable, dependent: :destroy

  scope :archived_for_user, ->(user) { where(status: 2, driver: user) }
  scope :taken_by_driver, ->(user) { where(status: 1, driver: user) }

  validates :date, :destination, :price, :start, :weight, presence: true

  self.per_page = 15

  def format_date
    date.strftime('%d/%m/%Y')
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :counter, only: %i[delivered index taken]
  before_action :set_order, only: %i[change_status edit show update destroy]

  def new
    @order = Order.new
  end

  def create
    @order = current_user.orders.new(order_params).decorate

    if @order.save
      User.drivers.each do |user|
        @order.create_notification(user, current_user, t('.created'))
      end
      redirect_to @order, notice: t('orders.created')
    else
      render :new
    end
  end

  def edit; end

  def index
    @active = :index
    @orders = Order.new_order.order(created_at: :desc).paginate(page: params[:page])

    @user_orders = current_user.orders.new_order.paginate(page: params[:page])
  end

  def show; end

  def update
    if @order.update(order_params)
      redirect_to @order
    else
      render :edit
    end
  end

  def destroy
    @order.destroy
    redirect_to orders_path, alert: t('orders.deleted')
  end

  def archive
    @archived_orders = Order.archived_for_user(current_user)
      .paginate(page: params[:page])
  end

  def change_status
    @order.update(status: params[:status], driver_id: params[:driver_id])

    if @order.taken?
      flash[:notice] = t('common.you_take_order')
      @order.create_notification(@order.user, current_user, t('.taken'))
    elsif @order.delivered?
      flash[:warning] = t('common.add_to_archive')
      @order.create_notification(@order.user, current_user, t('.delivered'))
    else
      flash[:alert] = t('common.you_refused_order')
      @order.create_notification(@order.user, current_user, t('.refused'))
    end

    redirect_back(fallback_location: root_path)
  end

  def delivered
    @active = :delivered
    @orders = Order.delivered.paginate(page: params[:page])
  end

  def taken
    @active = :taken
    @orders = Order.taken.paginate(page: params[:page])
  end

  def taken_orders
    @taken_orders = Order.taken_by_driver(current_user).order(date: :asc)
      .paginate(page: params[:page])
  end

  private

  def counter
    @count = current_user.orders.count
  end

  def order_params
    params.require(:order).permit(:comment, :destination, :date, :price, :start, :weight)
  end

  def set_order
    @order = Order.find(params[:id]).decorate
  end
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
  def format_price(value)
    number_to_currency(value, unit: t('helpers.uah'), format: '%n%u', precision: 0)
  end

  def format_weight(value)
    number_to_currency(value, unit: t('helpers.weight'), format: '%n%u', precision: 0)
  end

  def status_i18n(status)
    case status
    when 'new_order'
      t('status.new')
    when 'taken'
      t('status.taken')
    when 'delivered'
      t('status.delivered')
    end
  end
end

app/views/orders/_driver_control_links.html.erb
<% if @order.taken? %>
  <%= link_to t('common.delivered'), change_status_path(id: @order,
        status: 'delivered', driver_id: current_user), class: "btn btn-info" %>
  <%= link_to t('common.refuse'), change_status_path(id: @order,
        status: 'new_order', driver_id: nil), class: "btn btn-info" %>
<% else %>
  <%= link_to t('common.take_order'), change_status_path(id: @order,
        status: 'taken', driver_id: current_user), class: "btn btn-info" unless @order.delivered? %>
<% end %>

app/views/orders/_folder_view.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <%= render 'folders' %>
      </div>
    </div>
  </div>
  <div class="col-md-12 mt-3">
    <%= render 'orders/orders', orders: orders, f_title: t('orders.index.your_orders'), s_title: s_title %>
  </div>
</div>
<div class="text-center">
   <%= link_to t('orders.index.new_order'), new_order_path, class: "btn btn-info" unless current_user.driver? %>
</div>

app/views/orders/_folders.html.erb
<div class="index-list-group text-center">
  <%= link_to orders_path, class: "index-list-group-item #{active_page(:index)}" do %>
    <em class="fa fa-plus-square fa-lg"></em>
    <span><%= t('orders.index.new') %></span>
  <% end %>
  <%= link_to taken_path, class: "index-list-group-item #{active_page(:taken)}" do %>
    <em class="fa fa-thumb-tack fa-lg"></em>
    <span><%= t('orders.index.taken') %></span>
  <% end %>
  <%= link_to delivered_path, class: "index-list-group-item #{active_page(:delivered)}" do %>
    <em class="fa fa-truck fa-lg"></em>
    <span><%= t('orders.index.delivered') %></span>
  <% end %>
</div>

app/views/orders/_init_map.html.erb
<script type="text/javascript">
  var autocompleteFrom;
  var autocompleteTo;
  var mapFrom;
  var mapTo;
  var marker;
  var markersFrom = [];
  var markersTo = [];

  var elemFrom = document.getElementById('from');
  var inputFrom = $('#from');
  var mapFrom = document.getElementById('map-from');

  var elemTo = document.getElementById('to');
  var inputTo = $('#to');
  var mapTo = document.getElementById('map-to');

  function start(){
    initAutocomplete(elemFrom, inputFrom, mapFrom, markersFrom, mapFrom, autocompleteFrom);
    initAutocomplete(elemTo, inputTo, mapTo, markersTo, mapTo, autocompleteTo);
  }

  function initAutocomplete(elem, input, userMap, markersArray, map, autocomplete) {
    initMap();
    var infoWindow = new google.maps.InfoWindow({map: map});

    if (input.val().length > 0) {
      var geocoder = new google.maps.Geocoder;
      geocodeAddress(geocoder, input.val());
    } else {
      // Try HTML5 geolocation.
      if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(function(position) {
          var pos = {
            lat: position.coords.latitude,
            lng: position.coords.longitude
          };

          addMarker(pos, '<%= I18n.t('common.current_location') %>');
          map.setCenter(pos);
          map.setZoom(15);
        }, function() {
          handleLocationError(true, infoWindow, map.getCenter());
        });
      } else {
        // Browser doesn't support Geolocation
        handleLocationError(false, infoWindow, map.getCenter());
      }
    }

    function handleLocationError(browserHasGeolocation, infoWindow, pos) {
      infoWindow.setPosition(pos);
      infoWindow.setContent(browserHasGeolocation ? 'The Geolocation service disabled.' : 'Error: Your browser doesn\'t support geolocation.');
    }

    autocomplete = new google.maps.places.Autocomplete(
        /** @type {!HTMLInputElement} */(elem),
        {types: ['geocode']});

    autocomplete.addListener('place_changed', fillInAddress);

    function addMarker(location, info) {
      clearmarkersArray();

      var infoWindow = new google.maps.InfoWindow({map: map});
      var marker = new google.maps.Marker({
        position: location,
        map: map
      });

      markersArray.push(marker);
      infoWindow.open(map, marker);
      infoWindow.setContent(info);
      console.log('marker added');
    }

    function clearmarkersArray() {
      showmarkersArray(null);
      markersArray = [];
      console.log('markers array clear');
    }

    function fillInAddress() {
      initMap();

      var place = autocomplete.getPlace();

      addMarker(place.geometry.location, place.formatted_address)
      map.setCenter(place.geometry.location);
      map.setZoom(15);
      showmarkersArray(map);
    }

    function geocodeAddress(geocoder, address) {
      geocoder.geocode({'address': address}, function(results, status) {
        if (status === 'OK') {
          addMarker(results[0].geometry.location, address);
          map.setCenter(results[0].geometry.location);
          map.setZoom(15);
        } else {
          alert('Geocode was not successful for the following reason: ' + status);
        }
      });
    }

    function geocodeLatLng(geocoder, location) {
      geocoder.geocode({'location': location}, function(results, status) {
        if (status === 'OK') {
          if (results[0]) {
            input.val(results[0].formatted_address);
            addMarker(location, results[0].formatted_address);
          } else {
            window.alert('No results found');
          }
        } else {
          window.alert('Geocoder failed due to: ' + status);
        }
      });
    }

    function initMap() {
      var geocoder = new google.maps.Geocoder;
      var pos = {
        lat: <%= request.location.coordinates[0] %>,
        lng: <%= request.location.coordinates[1] %>
      }

      map = new google.maps.Map(userMap, {
        center: pos,
        zoom: 11
      });

      map.addListener('click', function(event) {
        geocodeLatLng(geocoder, event.latLng);
      });
    }

    function showmarkersArray(map) {
      markersArray.forEach(function(marker) {
        marker.setMap(map);
      });
    }
  }
</script>

app/views/orders/_orders.html.erb
<table class="table table-hover">
  <% if orders.present? %>
    <h2 class="text-center"><%= f_title %></h2>
    <tr>
      <th><%= t('orders.index.starting_point') %></th>
      <th><%= t('orders.index.destination_point') %></th>
      <th><%= t('orders.index.date') %></th>
      <th><%= t('orders.index.price') %></th>
      <th><%= t('orders.index.status') %></th>
      <th colspan="2"></th>
    </tr>

    <% orders.each do |order| %>
      <tr>
        <td><%= order.start %></td>
        <td><%= order.destination %></td>
        <td><%= order.format_date %></td>
        <td class="col-md"><%= format_price(order.price) %></td>
        <td style="color: green"><%= status_i18n(order.status) %></td>
        <td><%= link_to t('common.show'), order, class: "btn btn-light" %></td>
        <td>
          <%= link_to order_path(order),
                method: :delete, data: { confirm: t('common.confirm') }, title: t('common.delete'), class: "btn btn-light" do %>
            <%= fa_icon 'times' %>
          <% end  unless current_user.driver?  %>
        </td>
      </tr>
    <% end %>
  <% else %>
    <% if @count > 0 %>
      <h2 class="text-center"><%= s_title %></h2>
    <% else %>
      <h2 class="text-center"><%= t('orders.index.no_user_orders') %></h2>
    <% end %>
  <% end %>
</table>

app/views/orders/_route_and_distance.html.erb
<script>
  function DisplayRouteAndDistance() {
    var directionsService = new google.maps.DirectionsService;
    var directionsDisplay = new google.maps.DirectionsRenderer;
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 9,
      center: {lat: 49.0, lng: 32.0}
    });
    directionsDisplay.setMap(map);
    var onChangeHandler = function() {
      calculateAndDisplayRoute(directionsService, directionsDisplay);
    };
    onChangeHandler();

    var bounds = new google.maps.LatLngBounds;
    var markersArray = [];
    var origin1 = '<%= @order.start %>';
    var destinationA = '<%= @order.destination %>';
    var geocoder = new google.maps.Geocoder;
    var service = new google.maps.DistanceMatrixService;

    service.getDistanceMatrix({
      origins: [origin1],
      destinations: [destinationA],
      travelMode: 'DRIVING',
      unitSystem: google.maps.UnitSystem.METRIC
    }, function(response, status) {
      if (status !== 'OK') {
        alert('Error was: ' +  status);
      } else {
        var originList = response.originAddresses;
        var destinationList = response.destinationAddresses;
        var outputDiv = document.getElementById('output');
        outputDiv.innerHTML = '';
        deleteMarkersDistance(markersArray);
        for (var i = 0; i < originList.length; i++) {
          var results = response.rows[i].elements;
          distance = results[0].distance.text;
          time = results[0].duration.text;
          outputDiv.innerHTML += '<span>' + '<%= t('.distance') %>: ' + results[0].distance.text + '</span>' +
          '<span>' + '<%= t('.time_in_road') %>: ' +  results[0].duration.text + '</span>';
        }
      }
    });
  }

  function calculateAndDisplayRoute(directionsService, directionsDisplay) {
    directionsService.route({
      origin: '<%= @order.start %>',
      destination: '<%= @order.destination %>',
      travelMode: 'DRIVING'
    }, function(response, status) {
      if (status === 'OK') {
        directionsDisplay.setDirections(response);
      } else {
        window.alert('Directions request failed due to ' +  status);
      }
    });
  }

  function deleteMarkersDistance(markersArray) {
    for (var i = 0; i < markersArray.length; i++) {
      markersArray[i].setMap(null);
    }
    markersArray = [];
  }
</script>

<script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDjgTe57M-Jmvs1PfRM-a5xHQy9XTrTUlw&callback=DisplayRouteAndDistance">
</script>

app/views/orders/archive.html.erb
<% if @archived_orders.present? %>
  <h2 class="text-center"><%= t('.title') %></h2>
  <table class="table">
    <tr>
      <th><%= t('orders.index.starting_point') %></th>
      <th><%= t('orders.index.destination_point') %></th>
      <th><%= t('orders.index.date') %></th>
      <th class="col-md"><%= t('orders.index.price') %></th>
      <th><%= t('orders.index.status') %></th>
      <th colspan="2"></th>
    </tr>
    <% @archived_orders.each do |order| %>
      <tr>
        <td><%= order.start %></td>
        <td><%= order.destination%></td>
        <td><%= order.format_date %></td>
        <td><%= format_price(order.price) %></td>
        <td style="color: green"><%= status_i18n(order.status) %></td>
        <td><%= link_to t('common.show'), order, class: "btn btn-light" %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <h2 class="text-center"><%= t('.no_orders') %></h2>
<% end %>

<%= will_paginate @archived_orders %>

app/views/orders/delivered.html.erb
<%= render 'folder_view', orders: @orders, s_title: t('orders.index.delivered_none') %>

app/views/orders/edit.html.erb
<% provide(:title, t('title.edit_order')) %>

<h1 class="text-center"><%= t('orders.edit.title') %></h1>

<%= render 'form' %>

app/views/orders/index.html.erb
<% if current_user.driver? %>
  <%= render 'driver_orders', orders: @orders %>
<% else %>
  <%= render 'user_orders' %>
<% end %>

<%= will_paginate %>

app/views/orders/new.html.erb
<% provide(:title, t('title.new_order')) %>

<h1 class="text-center"><%= t('orders.new.title') %></h1>

<%= render 'form' %>

app/views/orders/show.html.erb
<div class="jumbotron">
  <p class="lead">
    <% if current_user.driver? %>
      <p class="text-center">
        <b>Заказчик: <%= link_to @order.user.full_name, user_path(@order.user) %></b><hr>
      </p>
    <% end %>
    <p><b><%= t('.starting_point') %>:    </b><%= @order.start %></p>
    <p><b><%= t('.destination_point') %>: </b><%= @order.destination %></p>
  </p>
  <hr class="my-4">
  <p><%= t('.price') %>:   <%= format_price(@order.price) %></p>
  <p><%= t('.date') %>:    <%= @order.format_date %></p>
  <p><%= t('.weight') %>:  <%= format_weight(@order.weight) %></p>
  <p><%= t('.status') %>:  <%= status_i18n(@order.status) %></p>
  <p><%= t('.comment') %>: <%= @order.comment %></p>

  <% if @order.driver.present? && current_user.not_driver? %>
    <p><b><%= t('common.user_taken_order') %></b> :
      <%= link_to @order.driver.full_name, user_path(@order.driver) %></p>
  <% end %>

  <p class="lead">
    <% if current_user.driver? %>
      <%= render 'driver_control_links' %>
    <% else %>
      <%= link_to t('common.edit'), edit_order_path(@order), class: "btn btn-info" %>
      <%= link_to t('common.delete'), order_path(@order), method: :delete, data: { confirm: t('common.confirm') }, class: "btn btn-info" %>
    <% end %>
  </p>

  <div class="map-panel">
    <div id="output"></div>
    <hr>
    <div id="map"></div>
  </div>
</div>

<%= render 'route_and_distance' %>

app/views/orders/taken.html.erb
<%= render 'folder_view', orders: @orders, s_title: t('orders.index.taken_none') %>

app/views/orders/taken_orders.html.erb
<% provide(:title, t('title.taken_orders')) %>

<% if @taken_orders.present? %>
  <h2 class="text-center"><%= t('common.taken_orders') %></h2>
  <table class="table">
    <tr>
      <th><%= t('.starting_point') %></th>
      <th><%= t('.destination_point') %></th>
      <th><%= t('.date') %></th>
      <th class="col-md"><%= t('.price') %></th>
      <th><%= t('.status') %></th>
      <th colspan="2"></th>
    </tr>
    <% @taken_orders.each do |order| %>
      <tr>
        <td><%= order.start %></td>
        <td><%= order.destination %></td>
        <td><%= order.format_date %></td>
        <td><%= format_price(order.price) %></td>
        <td style="color: green"><%= status_i18n(order.status) %></td>
        <td><%= link_to t('common.show'), order, class: "btn btn-light" %></td>
        <td><%= link_to t('common.refuse'), change_status_path(id: order, status: 'new_order', driver_id: nil), class: "btn btn-light" %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <h2 class="text-center"><%= t('.no_orders') %></h2>
<% end %>

<%= will_paginate @taken_orders %>